export default string = {
  login: "Login",
  emailaddress: "Email Address",
  password: "Password",
  back: "BACK",
  help: "HELP",
  invoices: "Invoices",
  customer: "Customers",
  products: "Products",
  payments: "Payments",
  addcustomer: "Add Customer",
  cancle: "CANCLE",
  delete: "DELETE",
  btnsubmit: "S U B M I T",
  btnupdate: "U P D A T E",
  btndone: "D O N E",
  btnsend: "S E N D",
  edit: "EDIT",
  customername: "Customer Name",
  phonenumber: "Phone No.",
  pannumber: "PAN No.",
  gstnumber: "GST No.",
  gststate: "GST State",
  gststatecode: "GST State Code",
  address: "Address",
  town: "Town / City",
  state: "State",
  customergstdetail: "Customer GST Details",
  billingaddress: "Billing Address",
  shippingaddress: "Shipping Address",
  shippingaddressasbilingaddress: "Shipping address is same as billing address",
  productname: "Product name",
  stock: "Stock",
  description: "Description",
  price: "Price",
  igst: "IGST",
  hsncode: "HSN code",
  addstock: "Add Stock",
  addproduct: "Add Product",
  choosefile: "Choose File",
  productdetail: "Product Detail",
  invoices: "Invoices",
  paid: "Paid",
  unpaid: "Unpaid",
  overdue: "OVERDUE",
  viewed: "VIEWED",
  createinvoice: "Create Invoice",
  draft: "Draft",
  projectname: "Project Name",
  posonumber: "P.O/S.O number",
  invoicedate: "Invoice date",
  paymentdue: "Payment Due",
  total: "Total",
  amountdue: "Amount Due",
  additem: "Add Item",
};
