export default string = {
  login: "Login",
  emailaddress: "Email Address",
  password: "Password",
  back: "BACK",
  help: "HELP",
  invoices: "Invoices",
  customer: "Customer",
  products: "Products",
  payments: "Payments",
  addcustomer: "Add Customer",
  cancle: "CANCLE",
  customername: "Customer Name",
  phonenumber: "Phone No.",
  pannumber: "PAN No.",
  gstnumber: "GST No.",
  gststate: "GST State",
  gststatecode: "GST State Code",
  address: "Address",
  town: "Town / City",
  state: "State",
  customergstdetail: "Customer GST Details",
  billingaddress: " Billing Address",
  shippingaddress: "Shipping address is same as billing address",
};
