import LocalizedStrings from "react-native-localization";

const StringsOfLanguage = new LocalizedStrings({
  en: {
    menu: "MENU",
    login: "Login",
    emailaddress: "Email Address",
    password: "Password",
    back: "BACK",
    help: "HELP",
    invoices: "Invoices",
    customer: "Customers",
    products: "Products",
    payments: "Payments",
    addcustomer: "Add Customer",
    cancle: "CANCLE",
    delete: "DELETE",
    btnsubmit: "S U B M I T",
    btnupdate: "U P D A T E",
    btndone: "D O N E",
    btnsend: "S E N D",
    edit: "EDIT",
    customername: "Customer Name",
    phonenumber: "Phone No.",
    pannumber: "PAN No.",
    gstnumber: "GST No.",
    gststate: "GST State",
    gststatecode: "GST State Code",
    address: "Address",
    town: "Town / City",
    state: "State",
    customergstdetail: "Customer GST Details",
    billingaddress: "Billing Address",
    shippingaddress: "Shipping Address",
    shippingaddressasbilingaddress:
      "Shipping address is same as billing address",
    productname: "Product name",
    stock: "Stock",
    description: "Description",
    price: "Price",
    igst: "IGST",
    hsncode: "HSN code",
    addstock: "Add Stock",
    addproduct: "Add Product",
    choosefile: "Choose File",
    productdetail: "Product Detail",
    paid: "Paid",
    unpaid: "Unpaid",
    overdue: "OVERDUE",
    viewed: "VIEWED",
    createinvoice: "Create Invoice",
    draft: "Draft",
    projectname: "Project Name",
    posonumber: "P.O/S.O number",
    invoicedate: "Invoice date",
    paymentdue: "Payment Due",
    total: "Total",
    amountdue: "Amount Due",
    additem: "Add Item",

    onboard1: "This is rupee sign and this screen is for demo only.!",
    onboard2: "This is eye sign and this screen is for demo only.!",
  },
  gu: {
    menu: "મેનુ",
    login: "પ્રવેશ કરો",
    emailaddress: "ઈ - મેઈલ સરનામું",
    password: "પાસવર્ડ",
    back: "પાછા",
    help: "મદદ",
    invoices: "ચલણ",
    customer: "ગ્રાહકો",
    products: "ઉત્પાદનો",
    payments: "ચુકવણીઓ",
    addcustomer: "ગ્રાહક ઉમેરો",
    cancle: "રદ કરો",
    delete: "કાઢી નાખો",
    btnsubmit: "S U B M I T",
    btnupdate: "U P D A T E",
    btndone: "D O N E",
    btnsend: "S E N D",
    edit: "સંપાદિત કરો",
    customername: "ગ્રાહક નું નામ",
    phonenumber: "ફોન નંબર",
    pannumber: "પાન નંબર",
    gstnumber: "GST નંબર",
    gststate: "GST રાજ્ય",
    gststatecode: "GST રાજ્ય કોડ",
    address: "સરનામું",
    town: "નગર / શહેર",
    state: "રાજ્ય",
    customergstdetail: "ગ્રાહક GST વિગતો",
    billingaddress: "બિલિંગ સરનામું",
    shippingaddress: "પહોંચાડવાનું સરનામું",
    shippingaddressasbilingaddress: "શિપિંગ સરનામું બિલિંગ સરનામા જેવું જ છે",
    productname: "ઉત્પાદન નામ",
    stock: "સ્ટોક",
    description: "વર્ણન",
    price: "કિંમત",
    igst: "IGST",
    hsncode: "HSN કોડ",
    addstock: "સ્ટોક ઉમેરો",
    addproduct: "ઉત્પાદન ઉમેરો",
    choosefile: "ફાઇલ પસંદ કરો",
    productdetail: "ઉત્પાદન વિગતો",
    paid: "ચૂકવેલ",
    unpaid: "અવેતન",
    overdue: "મુદત બહારનું",
    viewed: "જોયેલું",
    createinvoice: "ચલણ બનાવો",
    draft: "હૂંડી",
    projectname: "યોજનાનું નામ",
    posonumber: "P.O/S.O નંબર",
    invoicedate: "ચલણ તારીખ",
    paymentdue: "ચૂકવણી બાકી",
    total: "કુલ",
    amountdue: "બાકી નીકળતી રકમ",
    additem: "વસ્તુ ઉમેરો",

    onboard1: "This is rupee sign and this screen is for demo only.!",
    onboard2: "This is eye sign and this screen is for demo only.!",
  },
  hi: {
    menu: "मेन्यू",
    login: "लॉग इन करें",
    emailaddress: "मेल पता",
    password: "पासवर्ड",
    back: "पीछे",
    help: "मदद",
    invoices: "चालान",
    customer: "ग्राहकों",
    products: "उत्पादों",
    payments: "भुगतान",
    addcustomer: "ग्राहक जोड़ें",
    cancle: "रद्द करें",
    delete: "मिटाना",
    btnsubmit: "S U B M I T",
    btnupdate: "U P D A T E",
    btndone: "D O N E",
    btnsend: "S E N D",
    edit: "संपादन करना",
    customername: "ग्राहक का नाम",
    phonenumber: "फ़ोन नंबर",
    pannumber: "पैन नंबर",
    gstnumber: "GST नंबर",
    gststate: "GST राज्य",
    gststatecode: "GST राज्य कोड",
    address: "पता",
    town: "नगर / शहर",
    state: "राज्य",
    customergstdetail: "ग्राहक जीएसटी विवरण",
    billingaddress: "बिल भेजने का पता",
    shippingaddress: "भेजने का पता",
    shippingaddressasbilingaddress: "भेजने का पता बिलिंग पते के समान है",
    productname: "उत्पाद का नाम",
    stock: "भंडार",
    description: "विवरण",
    price: "कीमत",
    igst: "IGST",
    hsncode: "HSN कोड",
    addstock: "स्टॉक जोड़ें",
    addproduct: "उत्पाद जोड़ें",
    choosefile: "फाइलें चुनें",
    productdetail: "वास्तु की बारीकी",
    paid: "चुकाया गया",
    unpaid: "अवैतनिक",
    overdue: "बाकी",
    viewed: "देखा गया",
    createinvoice: "चालान बनाएँ",
    draft: "प्रारूप",
    projectname: "परियोजना का नाम",
    posonumber: "P.O/S.O संख्या",
    invoicedate: "चालान की तारीख",
    paymentdue: "भुगतान राशि",
    total: "कुल",
    amountdue: "देय राशि",
    additem: "वस्तु जोड़ें",

    onboard1: "This is rupee sign and this screen is for demo only.!",
    onboard2: "This is eye sign and this screen is for demo only.!",
  },
});
export default StringsOfLanguage;
