export const CLEAR_ALL = "CLEAR_ALL";
export const SAVE_LOGIN = "SAVE_LOGIN";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const CREATE_CUSTOMER = "CREATE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const GET_SELECTED_CUSTOMER = "GET_SELECTED_CUSTOMER";

export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_SELECTED_PRODUCTS = "GET_SELECTED_PRODUCTS";

export const GET_INVOICE = "GET_INVOICE";
export const CREATE_INVOICE = "CREATE_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
