export const CustomerDummyData = [
  {
    name: "A Dummy 1",
    phonenumber: "1234567890",
    emailaddress: "Dummy1@Dummy1.in",
    pannumber: "BNZPM2501F",
    gstnumber: "24AAACC1206D1ZM",
    gststate: "Gujarat",
    gststatecode: "24",
    address: "73",
    town: "Surat",
    state: "Gujarat",
    address1: "73",
    town1: "Surat",
    state1: "Gujarat",
  },
  {
    name: "B Dummy 2",
    phonenumber: "0987654321",
    emailaddress: "Dummy2@Dummy2.in",
    pannumber: "BNZPM2502F",
    gstnumber: "24AAACC1206D2ZM",
    gststate: "Goa",
    gststatecode: "25",
    address: "73",
    town: "Thivim",
    state: "Goa",
    address1: "12",
    town1: "Thivim",
    state1: "Goa",
  },
  {
    name: "C Dummy 3",
    phonenumber: "9898123123",
    emailaddress: "Dummy3@Dummy3.in",
    pannumber: "BNZPM2503F",
    gstnumber: "24AAACC1206D3ZM",
    gststate: "Delhi",
    gststatecode: "26",
    address: "45",
    town: "Noida",
    state: "Delhi",
    address1: "45",
    town1: "Noida",
    state1: "Delhi",
  },
];
export const ProductDummyData = [
  {
    id: 1,
    productname: "Accessories",
    price: 250,
    stock: 1,
    description: "All Mobile accessories",
    igst: 18,
    hsncode: 220,
  },
  {
    id: 2,
    productname: "Bluetooth",
    price: 2000,
    stock: 1,
    description: "Bluetooth HeadPhone",
    igst: 16,
    hsncode: 250,
  },
  {
    id: 3,
    productname: "Book",
    price: 400,
    stock: 12,
    description: "Bestseller Book in india",
    igst: 14,
    hsncode: 100,
  },
  {
    id: 4,
    productname: "Earphone",
    price: 1000,
    stock: 11,
    description: "Wireless earphone",
    igst: 12,
    hsncode: 210,
  },
  {
    id: 5,
    productname: "Flower Pots",
    price: 150,
    stock: 0,
    description: "5 flower phone",
    igst: 17,
    hsncode: 120,
  },
  {
    id: 6,
    productname: "Dairy",
    price: 200,
    stock: 8,
    description: "Milk products at discount",
    igst: 18,
    hsncode: 200,
  },
];
/**{
      "id": "A61994FB71C84EE98FCCB143D2A007",
      "formid": "0F67C3749F5A2726979849B0D39D00",
      "name": "F30",
      "label": "Toggle Followed by text and photo",
      "labelDE": "",
      "labelFR": "",
      "labelES": "",
      "labelZH": "",
      "labelMY": "",
      "type": "toggle",
      "seloptions": "1:Yes|0:Needs Attention|2:N/A",
      "value": "",
      "rank": 29,
      "status": 0,
      "mandatory": 0,
      "onchange": "",
      "columnwidth": "",
      "hidden": 0,
      "exportid": ""
    }, */
